"""add_beta_signups_table

Revision ID: 30249cf41c0f
Revises: e2f1a3b5c7d9
Create Date: 2026-01-15 16:13:52.864407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30249cf41c0f'
down_revision: Union[str, Sequence[str], None] = 'e2f1a3b5c7d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beta_signups',
    sa.Column('id', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('whatsapp', sa.String(length=50), nullable=True),
    sa.Column('university', sa.String(length=100), nullable=False),
    sa.Column('campus', sa.String(length=100), nullable=True),
    sa.Column('other_university', sa.String(length=255), nullable=True),
    sa.Column('academic_level', sa.String(length=50), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=True),
    sa.Column('tools', sa.Text(), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('expectations', sa.Text(), nullable=True),
    sa.Column('referral', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.text('now()')),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('beta_signups')
    # ### end Alembic commands ###
