"""update survey schema

Revision ID: 5ea91711823d
Revises: 8f6b4bb227a6
Create Date: 2026-01-18 21:06:28.784469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ea91711823d'
down_revision: Union[str, Sequence[str], None] = '8f6b4bb227a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('operating_system', sa.String(length=100), nullable=True))
    op.add_column('survey_responses', sa.Column('browser', sa.String(length=100), nullable=True))
    op.add_column('survey_responses', sa.Column('content_source', sa.String(length=255), nullable=True))
    op.add_column('survey_responses', sa.Column('visual_style', sa.String(length=255), nullable=True))
    op.drop_column('survey_responses', 'slide_frequency')
    op.drop_column('survey_responses', 'university')
    op.drop_column('survey_responses', 'pain_points')
    op.drop_column('survey_responses', 'course')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey_responses', sa.Column('course', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('pain_points', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('university', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('survey_responses', sa.Column('slide_frequency', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('survey_responses', 'visual_style')
    op.drop_column('survey_responses', 'content_source')
    op.drop_column('survey_responses', 'browser')
    op.drop_column('survey_responses', 'operating_system')
    # ### end Alembic commands ###
