"""Add survey_responses table

Revision ID: 8f6b4bb227a6
Revises: f1a2b3c4d5e6
Create Date: 2026-01-17 20:40:00.913796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8f6b4bb227a6'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_responses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('university', sa.String(length=255), nullable=True),
    sa.Column('course', sa.String(length=255), nullable=True),
    sa.Column('citation_style', sa.String(length=100), nullable=True),
    sa.Column('slide_frequency', sa.String(length=100), nullable=True),
    sa.Column('pain_points', sa.Text(), nullable=True),
    sa.Column('additional_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_survey_responses_email'), 'survey_responses', ['email'], unique=False)
    # Note: Removed auto-generated drop statements for layout_presets and slide_templates.university_id
    # These tables/columns should be preserved
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_survey_responses_email'), table_name='survey_responses')
    op.drop_table('survey_responses')
    # ### end Alembic commands ###

