"""add_playground_sessions_and_failure_reports

Revision ID: 978303058cb2
Revises: 
Create Date: 2025-12-21 17:52:55.667585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '978303058cb2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playground_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('flow_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_form', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skeleton', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('planned_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('refined_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_slides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_stage', sa.String(length=50), nullable=True),
    sa.Column('qa_loops_count', sa.Integer(), nullable=True),
    sa.Column('helper_retries', sa.Integer(), nullable=True),
    sa.Column('final_qa_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('failure_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('failing_agent', sa.String(length=50), nullable=False),
    sa.Column('failure_type', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('agent_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('agent_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('helper_attempts', postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['playground_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('firebase_uid', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('photo_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('university_profile', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('subscription_tier', sa.TEXT(), server_default=sa.text("'free'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('firebase_uid', name='users_firebase_uid_unique', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('mode', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'draft'::text"), autoincrement=False, nullable=True),
    sa.Column('contract_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('slides_json', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('projects_user_id_users_id_fk'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('projects_pkey'))
    )
    op.drop_table('failure_reports')
    op.drop_table('playground_sessions')
    # ### end Alembic commands ###
