"""add_css_overrides_to_theme_configs

Revision ID: bd7829c63554
Revises: d667c397dc47
Create Date: 2026-01-09 14:47:34.915657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd7829c63554'
down_revision: Union[str, Sequence[str], None] = 'd667c397dc47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('theme_configs', sa.Column('css_overrides', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('theme_configs', 'css_overrides')
    # ### end Alembic commands ###
