"""add_pdf_cache_table

Revision ID: c5b57642a774
Revises: 44ddb92483d2
Create Date: 2025-12-25 16:28:13.052240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c5b57642a774'
down_revision: Union[str, Sequence[str], None] = '44ddb92483d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdf_cache',
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('r2_key', sa.String(length=500), nullable=False),
    sa.Column('knowledge_base', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sections_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('file_hash')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdf_cache')
    # ### end Alembic commands ###
