"""add_template_system

Revision ID: d667c397dc47
Revises: fb85f344a4ea
Create Date: 2026-01-08 23:55:47.514025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd667c397dc47'
down_revision: Union[str, Sequence[str], None] = 'fb85f344a4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slide_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('html_template', sa.Text(), nullable=False),
    sa.Column('css_styles', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slide_templates_template_id'), 'slide_templates', ['template_id'], unique=True)
    op.create_table('theme_palettes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('theme_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('palette_id', sa.UUID(), nullable=True),
    sa.Column('typography', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('spacing', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('borders', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['palette_id'], ['theme_palettes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_theme_configs_theme_id'), 'theme_configs', ['theme_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_theme_configs_theme_id'), table_name='theme_configs')
    op.drop_table('theme_configs')
    op.drop_table('theme_palettes')
    op.drop_index(op.f('ix_slide_templates_template_id'), table_name='slide_templates')
    op.drop_table('slide_templates')
    # ### end Alembic commands ###
