"""add_cached_citations

Revision ID: fb85f344a4ea
Revises: c8f2a1b3e5d7
Create Date: 2026-01-08 22:55:17.920665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb85f344a4ea'
down_revision: Union[str, Sequence[str], None] = 'c8f2a1b3e5d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_citations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normalized_query', sa.String(length=500), nullable=False),
    sa.Column('doi', sa.String(length=255), nullable=True),
    sa.Column('arxiv_id', sa.String(length=50), nullable=True),
    sa.Column('citation_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cached_citations_arxiv_id'), 'cached_citations', ['arxiv_id'], unique=False)
    op.create_index(op.f('ix_cached_citations_doi'), 'cached_citations', ['doi'], unique=True)
    op.create_index(op.f('ix_cached_citations_normalized_query'), 'cached_citations', ['normalized_query'], unique=False)
    op.drop_index(op.f('ix_users_university_id'), table_name='users')
    op.drop_column('users', 'programme_id')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'academic_year')
    op.drop_column('users', 'presentation_context')
    op.drop_column('users', 'academic_level')
    op.drop_column('users', 'faculty_id')
    op.drop_column('users', 'department_id')
    op.drop_column('users', 'university_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('university_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('department_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('faculty_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('academic_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('presentation_context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('academic_year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('onboarding_completed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('programme_id', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_university_id'), 'users', ['university_id'], unique=False)
    op.drop_index(op.f('ix_cached_citations_normalized_query'), table_name='cached_citations')
    op.drop_index(op.f('ix_cached_citations_doi'), table_name='cached_citations')
    op.drop_index(op.f('ix_cached_citations_arxiv_id'), table_name='cached_citations')
    op.drop_table('cached_citations')
    # ### end Alembic commands ###
